version: '3'
services:
  web:
    image: nba-rosters-service
    build: .
    command: "node server.js"
    ports: 
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.5
    ports:
      - 27017:27017
    